### ISSUE TITLE
Add ReplaySorcery

### ISSUE THREAD

**Issue by spannerman79** [AdelKS/LinuxGamingGuide#2]
I'm not at my main system and I won't be for some time otherwise I would have done a PR.

You can add ReplaySorcery ( https://github.com/matanui159/ReplaySorcery ) to your guide.

It can also be configured via GOverlay

**Comment by AdelKS** [comment]
Hello! Thank you for the addition suggestion, a great one! I will add it :)

**Comment by AdelKS** [comment]
I added a paragraph about it. If you want anything else written in it, do tell!
